import type { ToolRegistry } from "../../application/tool/registry.js";
import { zodToLuauType } from "./zod-luau-type.js";

function kebabToCamel(s: string): string {
  return s.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase());
}

/**
 * Emit a full `mcp.d.luau` declaration from the live tool registry. The result
 * is consumable by Luau LSP — operators can drop it next to their scripts and
 * get autocomplete + hover on `mcp.<tool>(args)` everywhere, not just in the
 * in-browser REPL.
 *
 * Each tool's input Zod schema is converted to a Luau type alias; the `mcp`
 * table is then declared as a record of `(args: <Input>?) -> any` callables.
 */
export function emitMcpLuauTypes(registry: ToolRegistry): string {
  const tools = registry
    .list()
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name));

  const aliasLines: string[] = [];
  const methodLines: string[] = [];

  for (const tool of tools) {
    const aliasName = "Mcp_" + kebabToCamel(tool.name).replace(/^([a-z])/, (m) => m.toUpperCase()) + "Input";
    let luauType: string;
    try {
      luauType = zodToLuauType(tool.input);
    } catch {
      luauType = "{[string]: any}";
    }
    aliasLines.push(`-- ${tool.title}`);
    if (tool.description) {
      // Quote-escape the description for the doc comment; keep it on one line.
      const oneLine = tool.description.replace(/\s+/g, " ").trim();
      const trimmed = oneLine.length > 220 ? oneLine.slice(0, 217) + "..." : oneLine;
      aliasLines.push(`-- ${trimmed}`);
    }
    aliasLines.push(`export type ${aliasName} = ${luauType}`);
    aliasLines.push("");

    const camel = kebabToCamel(tool.name);
    methodLines.push(`  ${camel}: (args: ${aliasName}?) -> any,`);
  }

  return [
    "--!strict",
    "-- mcp.d.luau",
    "-- AUTO-GENERATED by the executor-mcp dashboard. Do not hand-edit.",
    `-- ${tools.length} tools across ${registry.categoryCounts().length} categories.`,
    "",
    aliasLines.join("\n"),
    "export type McpDeferred = { __mcpDeferred: boolean, tool: string, args: any }",
    "",
    "declare mcp: {",
    methodLines.join("\n"),
    "  -- Lower-level call by kebab name (when you have it as a string).",
    "  call: (name: string, args: any?) -> any,",
    "  -- Run multiple calls in parallel server-side via one rpc-batch frame.",
    "  -- spec entries can be { tool, args } / { tool=, args= } / a string tool",
    "  -- name / an McpDeferred from mcp.defer.",
    "  all: (spec: {[any]: any}) -> {[any]: any},",
    "  -- Alias for mcp.all.",
    "  parallel: (spec: {[any]: any}) -> {[any]: any},",
    "  -- Build a deferred call descriptor for use inside mcp.parallel/mcp.all.",
    "  defer: (name: string, args: any?) -> McpDeferred,",
    "}",
    "",
    "return mcp",
    "",
  ].join("\n");
}
